# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
  - job: ingestPricingData
    timeoutInMinutes: 480
    pool:
      name: selfhostedagent
    steps:
      - checkout: none
      - pwsh: | 
          Invoke-WebRequest -Uri https://mersenne-ovidiumihalcea.s3.eu-north-1.amazonaws.com/azurevms/MyTerraformStack.exe -OutFile MyTerraformStack.exe
          cdktf deploy --auto-approve
        displayName: 'Create Benchmarck Azure Compute'